### ISSUE TITLE
Update AirshipGimbalAdapter

### ISSUE THREAD

**Issue by AE1NS** [urbanairship/cordova-gimbal-bridge#13]
I am not able to install the pods when using this packages:
```
"urbanairship-cordova": "14.3.0",
"urbanairship-gimbal-bridge-cordova": "3.1.1",
```
```
[error] Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "Airship/ExtendedActions":
...
which depends on
Airship/ExtendedActions (= 16.8.0)
...
which depends on
AirshipGimbalAdapter (= 4.1.1) was resolved to 4.1.1, which depends on
Airship (= 16.7) was resolved to 16.7.0, which depends on
Airship/ExtendedActions (= 16.7.0)
```

It looks to me that `urbanairship-cordova` uses a dependency to `Airship/ExtendedActions 16.8.0` ([ref](https://github.com/urbanairship/urbanairship-cordova/blob/main/urbanairship-cordova/plugin.xml#L204)) and `urbanairship-gimbal-bridge-cordova` uses a dependency to `AirshipGimbalAdapter 4.1.1` ([ref](https://github.com/urbanairship/cordova-gimbal-bridge/blob/main/plugin.xml#L48)) which has a dependency to `Airship 16.7` ([ref](https://github.com/CocoaPods/Specs/blob/master/Specs/7/4/8/AirshipGimbalAdapter/4.1.1/AirshipGimbalAdapter.podspec.json#L29)).

Is it possible for you to update the AirshipGimbalAdapter with a dependency to Airship 16.8.0?

**Comment by Ulrico972** [comment]
Hello @AE1NS, the version 3.1.2 is out. Please let us know if everything works for you now.
