### ISSUE TITLE
Any way to tell if it's working?

### ISSUE THREAD

**Issue by tonymckendry** [urbanairship/cordova-gimbal-bridge#7]
So far, our tests have not worked but we have no way of telling which part is not working (app, urban airship, beacon, etc). 

Is there an event listener I can add to the app to fire something off so that I can at least tell if the app has found the beacon or not? 

Looking for something similar to this one from the Urban Airship Cordova docs: 

```
// Register for any Urban Airship events
document.addEventListener("urbanairship.registration", function (event) {
    if (event.error) {
        console.log('There was an error registering for push notifications')
    } else {
        console.log("Registered with ID: " + event.channelID)
    }
})
```

**Comment by rlepinski** [comment]
You can enable verbose logs and look for region events being added to the system. Thats the only thing we expose for this.

**Comment by tonymckendry** [comment]
@rlepinski - should this happen with ANY beacon or does it need to be one registered with Gimbal and UrbanAirship? We are (obviously trying to test this from a local install first, is that going to cause a problem?

**Comment by rlepinski** [comment]
@tonymckendry I believe the Gimbal SDK only reacts to beacons registered to the app.

**Comment by tonymckendry** [comment]
@rlepinski sorry for taking so long to get back to you 

We have enabled the verbose log level with the airship sdk - however when I turn the beacon on with my phone nearby I never see the logs you linked to. I'm not totally sure what is wrong at this point. 

One question I had: the Gimbal API key that I need to add to my mobile-config mentioned in the readme, is that the server api key from gimbal (that we also added to urban airship) or is it an app specific one that we need to create on the gimbal side?

**Comment by rlepinski** [comment]
@tonymckendry It should be your Ap's api key from Gimbal. Are you getting any errors logged from the Gimbal SDK?

**Comment by tonymckendry** [comment]
If i do a `logcat | grep gimbal` while my app is running on android I get the following messages: 

`UALib: Found com.urbanairship.gimbal_api_key in config.xml with value: <api key>`

`Found com.urbanairship.gimbal_auto_start in config.xml with value: true`

occasionally I will also get messages like these: 

`ApplicationPackageManager: load=com.gimbal.beaconmanager, bg=144-144, dr=200-200, forDefault=true, density=0`

`ApplicationPackageManager: load=com.gimbal.beaconmanager-crop, bg=200-200, dr=200-200`

As far as I can tell, those are the only messages I am getting. 

Also, I am still not entirely clear on your answer about the API key - Gimbal has a 'server api key' which we have to add to our Urban Airship settings for our app, but I believe you can also make individual 'applications' within gimbal which also have their own, platform-specific, api keys. Which one do I need to add to our cordova mobile-config?

**Comment by tonymckendry** [comment]
Also, you mentioned the Gimbal SDK, which is not listed as one of the requirements of this package (Cordova 5.4.0+, and Cordova iOS 3.9.0+, urbanairship-cordova plugin) - do we need to have the Gimbal SDK implemented as well? 

Is this the package we should be using? https://github.com/urbanairship/cordova-gimbal-sdk

We had already tried adding this as well, but didn't have any more luck.

**Comment by rlepinski** [comment]
This library is a simple wrapper around Gimbal that forwards events to UA. We are not Gimbal, these questions are better served for the Gimbal team. However they do not support Cordova so I am not sure how helpful they will be.

This plugin has a dependency on https://github.com/urbanairship/cordova-gimbal-sdk, so by using it, it installs the gimbal SDK. The API key is the app level one within from Gimbal. Do you have an active beacon or geofence that you are in? Does your gimbal api key work with Gimbals sample apps?

**Comment by tonymckendry** [comment]
I do have a beacon that we purchased to test with - Gimbal has indicated to me that I should be able to trigger enter and exit events by turning it on and off with my device nearby. 

We hadn't set up individual apps within Gimbal so I will try that and see if it makes a difference. Thanks!

**Comment by tonymckendry** [comment]
@rlepinski thanks again for your help - the Application specific API key seemed to solve our problem. I appreciate you bearing with me through these trials!
