### ISSUE TITLE
Issue running latest + request for better capacitor support

### ISSUE THREAD

**Issue by AE1NS** [urbanairship/cordova-gimbal-bridge#9]
After doing an Android fix for the cordova gimbal sdk plugin (see https://github.com/urbanairship/cordova-gimbal-sdk/issues/5), I get the next issue.

Will this plugin be updated to support the airship version of this https://github.com/urbanairship/urbanairship-cordova plugin? Inside the GimbalAdapter.java I get an issue with this line:
`import com.urbanairship.location.RegionEvent;`
because it cant be resolved.

**Comment by Ulrico972** [comment]
Hello @AE1NS 
I noticed you use also our cordova gimbal sdk plugin (https://github.com/urbanairship/cordova-gimbal-sdk). This is in fact just an implementation of the Gimbal SDK. I get that this is a bit confusing and we'll make sure it's more clear for the future.

I would recommend you to just use our Gimbal bridge plugin instead (https://github.com/urbanairship/cordova-gimbal-bridge) because it's implementing the Airship gimbal integration.

Concerning your issue on the Gimbal bridge plugin, I'll take a look and come back to you as soon as possible.

**Comment by AE1NS** [comment]
I just recognized that this version in this repository holds the version 3, but the published one on npm is still version 2, so I have to test it again.

**Comment by AE1NS** [comment]
I get this error when I install v3 directly from the repo.
```
Manifest merger failed : android:exported needs to be explicitly specified for <service>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.
```

**Comment by AE1NS** [comment]
I have another query: As we are using capacitor js, we have to set the gimbal key for the cordova with help of capacitors config file (https://capacitorjs.com/docs/config) (cordova - preferences). Unfortunately, we cant differ here between ios and android, so we can just set one api key here, but gimbal needs a specific one for ios and another for android.

I know its not a good approach in general, but is it possible to add an additional "fallback" for capacitor users, to set something like 'com.urbanairship.gimbal_api_key_ios' and 'com.urbanairship.gimbal_api_key_android'?

**Comment by AE1NS** [comment]
@Ulrico972 do you have any news?

**Comment by Ulrico972** [comment]
Hi @AE1NS,
We are still working on our gimbal adapters and bridge to make sure it's up to date and easy to use.
I should have some news for you during this week.

**Comment by Ulrico972** [comment]
Hi @AE1NS,
Maybe you can test this branch already if you need too: MOBILE-3128
There is a PR up but we are waiting for a few more members of the team to review it before I release the changes.
It shouldn't be so long anymore.

**Comment by AE1NS** [comment]
I will test it soon. If there are any more issues, I will create a new ticket. Do you gonna update it on npm also? https://www.npmjs.com/package/urbanairship-gimbal-bridge-cordova

**Comment by Ulrico972** [comment]
Yes, it has been published on npm today.

**Comment by AE1NS** [comment]
Thank you for the update!
Maybe you should also extend the Readme file with a hint to the optionally separated ios and android keys.

### Android
I get the following output when starting the app:
```
I/UAGimbalPlugin: Initializing Urban Airship Gimbal cordova plugin.
I/OBHMarketplace - UALib: Airship taking off!
I/OBHMarketplace - UALib: Airship log level: 3
I/OBHMarketplace - UALib: UA Version: 16.5.0 / App key = MUSvDE0jTo2EWOSmTAlwEg Production = false
I/-----: Using android logger factory
W/.obh.mp.app.de: Class com.gimbal.sdk.a0.e failed lock verification and will run slower.
ized dex code
D/OBHMarketplace Channel ID: 0db99dc1-2d83-4561-a3ca-3c5858752ac5
D/OBHMarketplace - UALib: Analytics - New session: 3569c6b3-6544-48df-b1e7-73db30c6d483
D/OBHMarketplace - UALib: Inbox - Updating user.
I/OBHMarketplace - UALib: Airship ready!
D/ConnectivityManager: StackLog: [android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:4090)] [android.net.ConnectivityManager.registerDefaultNetworkCallbackForUid(ConnectivityManager.java:4654)] [android.net.ConnectivityManager.registerDefaultNetworkCallback(ConnectivityManager.java:4621)] [android.net.ConnectivityManager.registerDefaultNetworkCallback(ConnectivityManager.java:4595)] [com.urbanairship.automation.NetworkMonitor.registerNetworkCallback(NetworkMonitor.java:51)] [com.urbanairship.automation.NetworkMonitor.setConnectionListener(NetworkMonitor.java:78)] [com.urbanairship.automation.AutomationEngine.start(AutomationEngine.java:285)] [com.urbanairship.automation.InAppAutomation.ensureStarted(InAppAutomation.java:818)] [com.urbanairship.automation.InAppAutomation.checkUpdatesSubscription(InAppAutomation.java:825)] [com.urbanairship.automation.InAppAutomation.onAirshipReady(InAppAutomation.java:277)] [com.urbanairship.UAirship.executeTakeOff(UAirship.java:431)] [com.urbanairship.UAirship.access$000(UAirship.java:66)] [com.urbanairship.UAirship$2.run(UAirship.java:379)] [java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)] [java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)] [com.urbanairship.util.AirshipThreadFactory$1.run(AirshipThreadFactory.java:50)] [java.lang.Thread.run(Thread.java:920)]
D/OBHMarketplace - UALib: AutomationEngine - Updating triggers with type: 8
D/ConnectivityManager: StackLog: [android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:4090)] [android.net.ConnectivityManager.registerDefaultNetworkCallbackForUid(ConnectivityManager.java:4654)] [android.net.ConnectivityManager.registerDefaultNetworkCallback(ConnectivityManager.java:4621)] [android.net.ConnectivityManager.registerDefaultNetworkCallback(ConnectivityManager.java:4595)] [androidx.work.impl.constraints.trackers.NetworkStateTracker.startTracking(NetworkStateTracker.java:89)] [androidx.work.impl.constraints.trackers.ConstraintTracker.addListener(ConstraintTracker.java:71)] [androidx.work.impl.constraints.controllers.ConstraintController.replace(ConstraintController.java:99)] [androidx.work.impl.constraints.WorkConstraintsTracker.replace(WorkConstraintsTracker.java:106)] [androidx.work.impl.background.greedy.GreedyScheduler.schedule(GreedyScheduler.java:157)] [androidx.work.impl.Schedulers.schedule(Schedulers.java:119)] [androidx.work.impl.utils.EnqueueRunnable.scheduleWorkInBackground(EnqueueRunnable.java:135)] [androidx.work.impl.utils.EnqueueRunnable.run(EnqueueRunnable.java:95)] [androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)] [java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)] [java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)] [java.lang.Thread.run(Thread.java:920)]
E/WM-WorkerWrapper: Didn't find WorkSpec for id f057c2b8-4863-4da6-bf8f-3ddff9d345fe
W/.obh.mp.app.de: Class com.gimbal.sdk.g1.c failed lock verification and will run slower.
W/G.b: [main                    ] Failed to un-register for passive location updates
I/UAGimbalPlugin: Auto starting Gimbal Adapter.
```

Do you know if I can ignore the `failed lock verification and will run slower` message?

### iOS
The build failed in XCode here. I get the following errors:
![grafik](https://user-images.githubusercontent.com/47378799/176120126-968f103a-bf4f-4a1d-a9aa-b18bf1f1a823.png)

Do I have to add any Gimbal SDK reference by myself to the podfile?

**Comment by Ulrico972** [comment]
Hello, I'm taking a look on your issue.
I come back to you as soon as possible.

**Comment by AE1NS** [comment]
XCode version 13.3.1

**Comment by Ulrico972** [comment]
I @AE1NS,
We published a new version of the plugin (3.1.1). I hope that one will work for you.
If it's not, do not hesitate to come back to us.

Concerning the Android warning, it seems like it's due to a non-optimized dex code or an incorrect proguard optimizations from the Gimbal SDK. It seems like it's there since a while on Gimbal.
I tried to fix it but I'm not sure we can even do it from the app side. So I think you can just ignore it for now.

**Comment by AE1NS** [comment]
Looks also good for iOS now!

Unfortunately I get this warning `The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.4.99.` but its running when I start the app and I also get the permission prompt.

Also notice the other point I wrote above: `Maybe you should also extend the Readme file with a hint to the optionally separated ios and android keys.`

**Comment by Ulrico972** [comment]
Hi,
Indeed Gimbal set the deployment target version at 9.0 in their podspec.
But you have the possibility to set or even remove the deployment target for your pods from your podfile: 

```
post_install do |installer|
 installer.pods_project.targets.each do |target|
  target.build_configurations.each do |config|
   config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
  end
 end
end
```

And I'll update the readme file, thanks for the reminder.
